name: buissenin
favicon: null
layout_spectrum: 0.8970271351281554
typography_spectrum: 0.24292831146158278
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.12584862229414284
  lightness: 0.5280567973386496
  saturation: 0.01333180209621787
  rhythmicContrast: 0.5604652415495366
purpose: []
